### PR TITLE
Update Swift6Mode.md

### PR DESCRIPTION
**Pull request by GangWoon**
I have added the section for setting the default language version in the example code to help those who prefer to understand by looking at the code first. Take seems good to you!

### CODE REVIEW

**Comment by mattmassicotte** [comment]
This change is technically unnecessary. Using the tools version as defined automatically changes the mode. The guide does try to cover this, because it is an important change. But, perhaps it is not clear enough?

**Comment by mattmassicotte** [comment]
> A `Package.swift` file that uses `swift-tools-version` of `6.0` will enable
the Swift 6 language mode for all targets.

**Comment by GangWoon** [comment]
@mattmassicotte 
When I looked at the guide document, I understood it the same way you mentioned. However, it didn't build with Swift 6.0, so I understood that the changes only apply when that parameter is modified.

**Comment by mattmassicotte** [comment]
Sorry this is so confusing, especially since the suggestion you are making is not wrong!

However, there is a known issue with Xcode 16 related to default language mode selection. This should get worked out and then will behave as documented here.

Thanks again, and please don't be shy about contributing more in the future!

**Pull request closed without merging**
